# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_ml_conversion/item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_ml_conversion/item.proto',
  package='core_ml_conversion',
  syntax='proto3',
  serialized_pb=_b('\n\x1d\x63ore_ml_conversion/item.proto\x12\x12\x63ore_ml_conversion\"#\n\x07ItemDef\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
)




_ITEMDEF = _descriptor.Descriptor(
  name='ItemDef',
  full_name='core_ml_conversion.ItemDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='core_ml_conversion.ItemDef.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='core_ml_conversion.ItemDef.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['ItemDef'] = _ITEMDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemDef = _reflection.GeneratedProtocolMessageType('ItemDef', (_message.Message,), dict(
  DESCRIPTOR = _ITEMDEF,
  __module__ = 'core_ml_conversion.item_pb2'
  # @@protoc_insertion_point(class_scope:core_ml_conversion.ItemDef)
  ))
_sym_db.RegisterMessage(ItemDef)


# @@protoc_insertion_point(module_scope)
