# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_ml_conversion/label.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_pb2 as core__ml__conversion_dot_item__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_ml_conversion/label.proto',
  package='core_ml_conversion',
  syntax='proto3',
  serialized_pb=_b('\n\x1e\x63ore_ml_conversion/label.proto\x12\x12\x63ore_ml_conversion\x1a\x1d\x63ore_ml_conversion/item.proto\"5\n\x08LabelDef\x12)\n\x04item\x18\x01 \x03(\x0b\x32\x1b.core_ml_conversion.ItemDefb\x06proto3')
  ,
  dependencies=[core__ml__conversion_dot_item__pb2.DESCRIPTOR,])




_LABELDEF = _descriptor.Descriptor(
  name='LabelDef',
  full_name='core_ml_conversion.LabelDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='core_ml_conversion.LabelDef.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=138,
)

_LABELDEF.fields_by_name['item'].message_type = core__ml__conversion_dot_item__pb2._ITEMDEF
DESCRIPTOR.message_types_by_name['LabelDef'] = _LABELDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabelDef = _reflection.GeneratedProtocolMessageType('LabelDef', (_message.Message,), dict(
  DESCRIPTOR = _LABELDEF,
  __module__ = 'core_ml_conversion.label_pb2'
  # @@protoc_insertion_point(class_scope:core_ml_conversion.LabelDef)
  ))
_sym_db.RegisterMessage(LabelDef)


# @@protoc_insertion_point(module_scope)
